#spring.application.name=spring2nd
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: root
    password: Gate@2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true


